# Generated by Django 3.1.7 on 2021-02-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='juez',
            options={'verbose_name_plural': 'Jueces'},
        ),
        migrations.AddField(
            model_name='juez',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=10),
        ),
    ]
