# Generated by Django 3.1.7 on 2021-02-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticas', '0002_auto_20210220_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDeAudiencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('preparatoria', 'A. PREPARATORIA'), ('juicio', 'A. DE JUICIO'), ('especial', 'ESPECIAL / INCIDENTAL / UNICA'), ('continuacion juicio', 'CONTINUACIÓN JUICIO'), ('continuacion preparatoria', 'CONTINUACIÓN PREPARATORIA'), ('continuacion especial', 'CONTINUACION ESPECIAL/INCIDENTAL'), ('inmediata', 'AUDIENCIA INMEDIATA')], max_length=40)),
            ],
        ),
    ]
