# Generated by Django 3.1.7 on 2021-04-03 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='OficioSalida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_oficio', models.DateField(auto_now=True)),
                ('rit', models.CharField(max_length=10)),
                ('referencia', models.CharField(max_length=20)),
                ('comuna', models.CharField(max_length=20)),
                ('fecha_envio', models.DateField()),
                ('codigo_envio', models.IntegerField()),
                ('forma_envio', models.CharField(choices=[('correo electrónico', 'correo electrónico'), ('correos de chile', 'correos de chile'), ('por mano', 'por mano')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'pendiente'), ('enviado', 'enviado'), ('anulado', 'anulado')], max_length=12)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='OficiosSalida')),
                ('institucion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='intra.institucion')),
            ],
        ),
        migrations.CreateModel(
            name='OficioEntrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_oficio', models.DateField()),
                ('fecha_recepcion', models.DateField(auto_now=True)),
                ('numero_oficio', models.IntegerField()),
                ('referencia', models.CharField(max_length=40)),
                ('observacion', models.CharField(max_length=140)),
                ('archivo', models.FileField(upload_to='OficiosEntrada')),
                ('institucion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='intra.institucion')),
            ],
        ),
    ]
